- label: 'Introduction'
  link: '/'
- label: Usage
  items:
    - label: 'useUndoRedo'
      link: '/usage/use-undo-redo'
    - label: 'useLogger'
      link: '/usage/use-logger'
    - label: 'useThunk'
      link: '/usage/use-thunk'
    - label: 'usePersist'
      link: '/usage/use-persist'
- label: Community
  items:
    - label: 'Github'
      link: https://github.com/jyash97/middleware-hooks
